#!/usr/bin/env python3
"""Regenerate every file that derives a value from project.toml.

Run it after editing project.toml:

    python3 scripts/sync_metadata.py

`--check` reports drift and exits non-zero instead of writing, which is what
`tests/metadata_ssot_tests.py` and CI use to prove nothing was hand-edited.

Files whose values come from the compiler build (include/quidra/project.hpp,
include/quidra/tooling.hpp) are generated by CMake at configure time and are
deliberately not handled here.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import toml_subset  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
PROJECT_TOML = ROOT / "project.toml"
MANIFEST = ROOT / "quidra.manifest.json"
README = ROOT / "README.md"


def manifest_fields(project: dict) -> dict:
    """The manifest keys owned by project.toml, in manifest key order."""
    meta = project["project"]
    return {
        "language": meta["name"],
        "language_version": meta["language_version"],
        "compiler_version": meta["version"],
        "tagline": meta["tagline"],
        "source_extension": meta["extension"],
        "canonical_repository": project["repos"]["core"],
        "repl_command": meta["cli"],
        "repl_explicit_command": f"{meta['cli']} repl",
        "supported_platforms": project["platforms"]["os"],
    }


def render_manifest(project: dict) -> str:
    data = json.loads(MANIFEST.read_text(encoding="utf-8"))
    owned = manifest_fields(project)
    missing = sorted(set(owned) - set(data))
    if missing:
        raise SystemExit(
            f"quidra.manifest.json is missing generated keys: {', '.join(missing)}"
        )
    data.update(owned)
    data["gpu_backend_model"]["abi_version"] = project["compat"]["abi"]
    package = project["package_manager"]
    data["package_manager_model"] = {
        "package_schema_version": project["compat"]["package_schema"],
        "lockfile_schema_version": project["compat"]["lockfile_schema"],
        "manifest_file": package["manifest_file"],
        "project_file": package["project_file"],
        "lock_file": package["lock_file"],
        "entrypoint": package["entrypoint_stem"] + project["project"]["extension"],
        "store_relative": package["store_relative"],
        "official_distribution_prefix": package["official_distribution_prefix"],
        "official_repository_base": package["official_repository_base"],
    }
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


def render_readme(project: dict) -> str:
    version = project["project"]["version"]
    name = project["project"]["name"]
    text = README.read_text(encoding="utf-8")
    # The REPL transcript prints the running compiler's banner; pinning a stale
    # version there is exactly the drift this file exists to prevent.
    return re.sub(
        rf"^{re.escape(name)} \d+\.\d+\.\d+$",
        f"{name} {version}",
        text,
        flags=re.MULTILINE,
    )


TARGETS = (
    (MANIFEST, render_manifest),
    (README, render_readme),
)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="report drift and exit non-zero instead of writing",
    )
    args = parser.parse_args()

    project = toml_subset.load(PROJECT_TOML)
    stale = []
    for path, render in TARGETS:
        rendered = render(project)
        if rendered == path.read_text(encoding="utf-8"):
            continue
        if args.check:
            stale.append(path.relative_to(ROOT))
        else:
            path.write_text(rendered, encoding="utf-8")
            print(f"updated {path.relative_to(ROOT)}")

    if stale:
        names = ", ".join(str(path) for path in stale)
        print(
            f"{names} disagree with project.toml.\n"
            "Edit project.toml and run: python3 scripts/sync_metadata.py",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
